name: Feature request
labels: enhancement
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
  - type: textarea
    id: rationale
    attributes:
      label: Why this matters
